"""permission_groups.name

Revision ID: 2317dc98a62b
Revises: 9574808865fa
Create Date: 2020-10-17 12:56:52.341686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2317dc98a62b'
down_revision = '9574808865fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission_groups', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission_groups', 'name')
    # ### end Alembic commands ###
