"""removed_user_content.timestamp

Revision ID: 66d28880394c
Revises: 2317dc98a62b
Create Date: 2020-10-18 21:37:01.430216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d28880394c'
down_revision = '2317dc98a62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('removed_user_content', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_removed_user_content_timestamp'), 'removed_user_content', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_removed_user_content_timestamp'), table_name='removed_user_content')
    op.drop_column('removed_user_content', 'timestamp')
    # ### end Alembic commands ###
