"""posts.arbitrary_hotness -> posts.hotness

Revision ID: 77e0c0edaa04
Revises: fdd9a12300fa
Create Date: 2020-10-22 15:29:20.846003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77e0c0edaa04'
down_revision = 'fdd9a12300fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('hotness', sa.Integer(), nullable=False))
    op.drop_column('posts', 'arbitrary_hotness')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('arbitrary_hotness', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('posts', 'hotness')
    # ### end Alembic commands ###
