"""posts.hotness

Revision ID: 7a4e8e75eda1
Revises: 66d28880394c
Create Date: 2020-10-22 12:13:34.785492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4e8e75eda1'
down_revision = '66d28880394c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('hotness', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'hotness')
    # ### end Alembic commands ###
