"""users.is_risky

Revision ID: 7d30366eb5ad
Revises: 4b12a7439333
Create Date: 2020-10-04 15:07:23.882184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d30366eb5ad'
down_revision = '4b12a7439333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_risky', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_risky')
    # ### end Alembic commands ###
