"""registered_users.permission_group_id, permission_groups

Revision ID: 9574808865fa
Revises: 7d30366eb5ad
Create Date: 2020-10-17 12:47:52.639321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9574808865fa'
down_revision = '7d30366eb5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.add_column('registered_users', sa.Column('permission_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'registered_users', 'permission_groups', ['permission_group_id'], ['id'])
    op.drop_column('registered_users', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_users', sa.Column('permission', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'registered_users', type_='foreignkey')
    op.drop_column('registered_users', 'permission_group_id')
    op.drop_table('permission_groups')
    # ### end Alembic commands ###
