"""posts.username

Revision ID: 9866eaad3787
Revises: ed75ea1c55f3
Create Date: 2020-11-02 11:59:42.058272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9866eaad3787'
down_revision = 'ed75ea1c55f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'username')
    # ### end Alembic commands ###
