"""RemovedUserMedia

Revision ID: e087046782c3
Revises: ff97c94d6ea7
Create Date: 2020-11-05 20:04:11.227689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e087046782c3'
down_revision = 'ff97c94d6ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('removed_user_media',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_media_id', sa.BigInteger(), nullable=True),
    sa.Column('moderator_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['registered_users.id'], ),
    sa.ForeignKeyConstraint(['user_media_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_removed_user_media_timestamp'), 'removed_user_media', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_removed_user_media_timestamp'), table_name='removed_user_media')
    op.drop_table('removed_user_media')
    # ### end Alembic commands ###
