"""Pre-add default admin

Revision ID: ed75ea1c55f3
Revises: 25fc8579e934
Create Date: 2020-10-29 14:26:20.153342

"""
from alembic import op
from sqlalchemy import Table, MetaData
import sqlalchemy as sa
from sqlalchemy.sql.schema import Column
from sqlalchemy.sql.sqltypes import Integer, String


# revision identifiers, used by Alembic.
revision = 'ed75ea1c55f3'
down_revision = '25fc8579e934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    conn = op.get_bind()
    meta = MetaData(bind=conn)

    registered_users_table = Table("registered_users", meta, Column("username", String), Column("password", String), Column("permission_group_id", Integer))
    permissions_table = Table("permission_groups", meta, Column("permissions", String), Column("name", String))

    op.bulk_insert(
        permissions_table,
        [
            { "permissions": "[0,1,2,3,4]", "name": "owner" }, 
            { "permissions": "[0,1,3,4]", "name": "mod" }, 
            { "permissions": "[0,2]", "name": "janitor" }
        ]
    )

    result = conn.execute("SELECT id FROM permission_groups WHERE name='owner'").fetchall()[0][0]
    op.bulk_insert(
        registered_users_table,
        [
            {"username": "YOUR_USERNAME", "password": "YOUR_BCRYPT_HASHED_PASSWORD", "permission_group_id": result, "token": None}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
