"""Changed foreginkey policy

Revision ID: f65a9db756fe
Revises: e087046782c3
Create Date: 2020-11-05 20:06:30.978378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65a9db756fe'
down_revision = 'e087046782c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('removed_user_media_ibfk_2', 'removed_user_media', type_='foreignkey')
    op.create_foreign_key(None, 'removed_user_media', 'user_media', ['user_media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'removed_user_media', type_='foreignkey')
    op.create_foreign_key('removed_user_media_ibfk_2', 'removed_user_media', 'posts', ['user_media_id'], ['id'])
    # ### end Alembic commands ###
