"""posts.hotness to posts.arbitrary_hotness

Revision ID: fdd9a12300fa
Revises: 7a4e8e75eda1
Create Date: 2020-10-22 13:07:52.873894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdd9a12300fa'
down_revision = '7a4e8e75eda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('arbitrary_hotness', sa.Integer(), nullable=False))
    op.drop_column('posts', 'hotness')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('hotness', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('posts', 'arbitrary_hotness')
    # ### end Alembic commands ###
