"""file_id

Revision ID: ff97c94d6ea7
Revises: 9866eaad3787
Create Date: 2020-11-03 22:08:17.321825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff97c94d6ea7'
down_revision = '9866eaad3787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_media', sa.Column('file_id', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_media', 'file_id')
    # ### end Alembic commands ###
